# Path for additional files to download
# per ubuntu per prendere i file : /var/www/gci/Flask_App/RIBOflaskapp/static/client/nomefile
"""
DBN_FILES = "C:\\Users\\Chiara\\OneDrive\\Desktop\\GP-Master\\GP_DA_GIT\\GroupProject-master\\website_management\\static\\client\\dbn_files"
DBN_FILES_NH = "C:\\Users\\Chiara\\OneDrive\\Desktop\\GP-Master\\GP_DA_GIT\\GroupProject-master\\website_management\\static\\client\\dbn_nH_files"
CT_FILES = "C:\\Users\\Chiara\\OneDrive\\Desktop\\GP-Master\\GP_DA_GIT\\GroupProject-master\\website_management\\static\\client\\ct_files"
CT_FILES_NH = "C:\\Users\\Chiara\\OneDrive\\Desktop\\GP-Master\\GP_DA_GIT\\GroupProject-master\\website_management\\static\\client\\ct_nH_files"
BPSEQ_FILES = "C:\\Users\\Chiara\\OneDrive\\Desktop\\GP-Master\\GP_DA_GIT\\GroupProject-master\\website_management\\static\\client\\bpseq_files"
BPSEQ_FILES_NH = "C:\\Users\\Chiara\\OneDrive\\Desktop\\GP-Master\\GP_DA_GIT\\GroupProject-master\\website_management\\static\\client\\bpseq_nH_files"
FASTA_FILES = "C:\\Users\\Chiara\\OneDrive\\Desktop\\GP-Master\\GP_DA_GIT\\GroupProject-master\\website_management\\static\\client\\fasta_files"
FASTA_FILES_NH = "C:\\Users\\Chiara\\OneDrive\\Desktop\\GP-Master\\GP_DA_GIT\\GroupProject-master\\website_management\\static\\client\\fasta_nH_files"
"""
DBN_FILES = "C:\\Users\\Denise\\Desktop\\Group Project\\GroupProject\\website_management\\static\\client\\dbn_files"
DBN_FILES_NH = "C:\\Users\\Denise\\Desktop\\Group Project\\GroupProject\\website_management\\static\\client\\dbn_nH_files"
CT_FILES = "C:\\Users\\Denise\\Desktop\\Group Project\\GroupProject\\website_management\\static\\client\\ct_files"
CT_FILES_NH = "C:\\Users\\Denise\\Desktop\\Group Project\\GroupProject\\website_management\\static\\client\\ct_nH_files"
BPSEQ_FILES = "C:\\Users\\Denise\\Desktop\\Group Project\\GroupProject\\website_management\\static\\client\\bpseq_files"
BPSEQ_FILES_NH = "C:\\Users\\Denise\\Desktop\\Group Project\\GroupProject\\website_management\\static\\client\\bpseq_nH_files"
FASTA_FILES = "C:\\Users\\Denise\\Desktop\\Group Project\\GroupProject\\website_management\\static\\client\\fasta_files"
FASTA_FILES_NH = "C:\\Users\\Denise\\Desktop\\Group Project\\GroupProject\\website_management\\static\\client\\fasta_nH_files"
